### ISSUE TITLE
Unable to replicate xai_evaluation

### ISSUE THREAD

**Issue by apurvakokate** [GiuseppeSerra93/L2XGNN#1]
The explanation performance especially accuracy and precision are lower than whats reported in the paper. Can you help me replicate the results. Perhaps specifying a random seed would help

**Comment by gserpep** [comment]
> The explanation performance especially accuracy and precision are lower than whats reported in the paper

For both datasets? Have you tried using a lower ratio? For Mutagenicity. a ratio of 0.5 should do the work. For BA2Motifs, you should use 0.4. 


> Can you help me replicate the results. Perhaps specifying a random seed would help

Are you using the latest version of the repo? We provided the splits used in the experiments in `xai_evaluation/datasets/data_splits/`.

**Comment by apurvakokate** [comment]
Thank you very much for reverting back to me.

*Firstly, I get the following error when running the latest code on master:
*
  File "/nfs/hpc/share/kokatea/L2XGNN/xai_evaluation/l2xgnn/graph_imle.py",
line 287, in forward
    sample = np.append(sample, sample_out.cpu())
AttributeError: 'NoneType' object has no attribute 'cpu'

*Since sample is only stored for backpropagation I modify the code as :*
if train_phase:
    sample = np.append(sample, sample_out.cpu())

*That is the only modification I made*, then I train the model using
python3 1_l2xgnn_train.py --dataset=ba_2motifs --model=L2XGIN
--connected=False --ratio=0.4 --split={}

*Here are the results for BA2-motif dataset:*
Epoch: 118, Test Acc: 0.9600
Accuracy:        0.656 ± 0.010 (Expected 80.0 ± 1.2)
Precision:       0.343 ± 0.013 (Expected 52.1 ± 1.6)
Recall:          0.653 ± 0.024 (Expected 94.7 ± 2.7 )
F1-score:        0.450 ± 0.017 (Expected 67.1 ± 2.0)

Please let me know if I am missing any step.

Regards,
Apurva
